# Generated by Django 5.0.2 on 2024-03-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name=' Часть ссылки (автозаполняется)')),
                ('image', models.ImageField(blank=True, default='lector/images/empty_lector.jpg', help_text='соотношение сторон - квадрат', null=True, upload_to='lector/images', verbose_name='Фотография')),
                ('specialization', models.CharField(default='стоматолог', max_length=100, verbose_name='Специализация')),
                ('short_desc', models.TextField(help_text='<1000 символов', max_length=1000, verbose_name='Короткое описание')),
                ('long_desc', models.TextField(help_text='<10000 символов', max_length=10000, verbose_name='Полное описание  (заголовок в формате <p class="h2 my-3"> День 1 </p>) ')),
            ],
            options={
                'verbose_name': 'Лектор',
                'verbose_name_plural': 'Лекторы',
                'db_table': 'lector',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Часть ссылки (автозаполняется)')),
                ('image', models.ImageField(blank=True, default='seminar/images/empty_seminar.jpg', null=True, upload_to='seminar/image', verbose_name='Картинка')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('type', models.CharField(default='лекция', max_length=50, verbose_name='лекция/практика')),
                ('food', models.CharField(default='кофе-брейк', max_length=50, verbose_name='обед/кофе-брей')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание (заголовок в формате <p class="h2 my-3"> День 1 </p>) ')),
                ('pricing', models.TextField(max_length=3000)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lector', to='main.lector', verbose_name='Лектор 1')),
                ('lector_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lector_2', to='main.lector', verbose_name='Лектор 2')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
                'db_table': 'seminar',
            },
        ),
    ]
