# Generated by Django 5.0.2 on 2024-03-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectors/images')),
                ('specialization', models.CharField(default='стоматолог', max_length=100)),
                ('short_desc', models.TextField(max_length=2000)),
                ('long_desc', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Лектор',
                'verbose_name_plural': 'Лекторы',
                'db_table': 'lector',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='seminar/images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='seminar/images')),
                ('background_image', models.ImageField(blank=True, default='seminar/background/background7.jpg', null=True, upload_to='seminar/background')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(default='лекция', max_length=50)),
                ('food', models.CharField(default='кофе-брейк', max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('price_desc', models.TextField(max_length=3000)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lector', to='main.lector')),
                ('lector_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='lector_2', to='main.lector')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
                'db_table': 'seminar',
            },
        ),
    ]
