# Generated by Django 5.0.2 on 2024-03-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectors/images')),
                ('specialization', models.CharField(default='стоматолог', max_length=100)),
                ('short_desc', models.TextField(max_length=300)),
                ('long_desc', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Лектор',
                'verbose_name_plural': 'Лекторы',
                'db_table': 'lector',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='seminar/images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='seminar/images')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('price_desc', models.TextField(max_length=2000)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lector')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
                'db_table': 'seminar',
            },
        ),
    ]
