# Generated by Django 5.0.2 on 2024-03-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='price_desc',
            new_name='pricing',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='lector_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lector_2', to='main.lector'),
        ),
    ]
