# Generated by Django 5.0.2 on 2024-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='food',
            field=models.CharField(default='кофе-брейк', max_length=50),
        ),
        migrations.AddField(
            model_name='seminar',
            name='type',
            field=models.CharField(default='лекция', max_length=50),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
